// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCZf5zDrSEquQ3Lqb_uquGrR8FTvxtyxw',
    appId: '1:537931363375:web:851408fa615921c32e82da',
    messagingSenderId: '537931363375',
    projectId: 'iot-notifications-c1ff3',
    authDomain: 'iot-notifications-c1ff3.firebaseapp.com',
    storageBucket: 'iot-notifications-c1ff3.appspot.com',
    measurementId: 'G-8SXJMS06RN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb9x1Amd8ZWlIlF9Tsrk-E2RO9ZxN9CUg',
    appId: '1:537931363375:android:3543b740e7d764872e82da',
    messagingSenderId: '537931363375',
    projectId: 'iot-notifications-c1ff3',
    storageBucket: 'iot-notifications-c1ff3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRR78kg30aeIoOQEzo4_Xeovxf1fvAC9k',
    appId: '1:537931363375:ios:57db7b100012b20c2e82da',
    messagingSenderId: '537931363375',
    projectId: 'iot-notifications-c1ff3',
    storageBucket: 'iot-notifications-c1ff3.appspot.com',
    iosClientId: '537931363375-14281b9sop4t2e909ma1kd0n1hqs81i4.apps.googleusercontent.com',
    iosBundleId: 'com.example.iotApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRR78kg30aeIoOQEzo4_Xeovxf1fvAC9k',
    appId: '1:537931363375:ios:57db7b100012b20c2e82da',
    messagingSenderId: '537931363375',
    projectId: 'iot-notifications-c1ff3',
    storageBucket: 'iot-notifications-c1ff3.appspot.com',
    iosClientId: '537931363375-14281b9sop4t2e909ma1kd0n1hqs81i4.apps.googleusercontent.com',
    iosBundleId: 'com.example.iotApp',
  );
}
